### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float

### ISSUE THREAD

**Issue by Khas-Erdene-1** [uw-ipd/RoseTTAFold2#38]
Hi,

I'm having following problem. I run with the example files, it was fine but when I input following fasta, it gives the error.
Any suggestions?

/data2/apps/RoseTTAFold2/run_RF2.sh /home/khasaa/projects/RoseTTAfold_ADAMTS13/Q76LX8.fasta -o Q76LX8
Running RoseTTAFold2 to predict structures
 -> Running command: python /data2/apps/RoseTTAFold2/network/predict.py -inputs Q76LX8/Q76LX8_1.msa0.a3m  -prefix Q76LX8/models/model -model /data2/apps/RoseTTAFold2/network/weights/RF2_jan24.pt -db /data2/apps/RoseTTAFold2/pdb100_2021Mar03/pdb100_2021Mar03 -symm C1
Running on GPU
N=2048 L=1427
recycle 0 plddt 0.308 pae 28.391 rmsd 34.750
Traceback (most recent call last):
  File "/data2/apps/RoseTTAFold2/network/predict.py", line 623, in <module>
    pred.predict(
  File "/data2/apps/RoseTTAFold2/network/predict.py", line 425, in predict
    self.run_prediction(
  File "/data2/apps/RoseTTAFold2/network/predict.py", line 510, in run_prediction
    logit_s, _, _, logits_pae, p_bind, xyz_prev, alpha, symmsub, pred_lddt, msa_prev, pair_prev, state_prev = self.model(
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/apps/RoseTTAFold2/network/RoseTTAFoldModel.py", line 115, in forward
    msa, pair, R, T, alpha, state, symmsub = self.simulator(
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/apps/RoseTTAFold2/network/Track_module.py", line 792, in forward
    msa_full, pair, R_in, T_in, state, alpha, symmsub = self.extra_block[i_m](
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/apps/RoseTTAFold2/network/Track_module.py", line 690, in forward
    R, T, state, alpha = self.str2str(
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/apps/RoseTTAFold2/network/Track_module.py", line 600, in forward
    shift = self.se3(G, node, l1_feats, edge_feats)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/data2/apps/RoseTTAFold2/network/SE3_network.py", line 86, in forward
    return self.se3(G, node_features, edge_features)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/se3_transformer-1.2.0-py3.10.egg/se3_transformer/model/transformer.py", line 187, in forward
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/se3_transformer-1.2.0-py3.10.egg/se3_transformer/model/transformer.py", line 47, in forward
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/se3_transformer-1.2.0-py3.10.egg/se3_transformer/model/layers/attention.py", line 158, in forward
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/se3_transformer-1.2.0-py3.10.egg/se3_transformer/model/layers/convolution.py", line 358, in forward
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/se3_transformer-1.2.0-py3.10.egg/se3_transformer/model/layers/convolution.py", line 245, in <lambda>
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/se3_transformer-1.2.0-py3.10.egg/se3_transformer/model/layers/convolution.py", line 181, in forward
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/se3_transformer-1.2.0-py3.10.egg/se3_transformer/model/layers/convolution.py", line 119, in forward
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    def forward(self, input):
        for module in self:
            input = module(input)
                    ~~~~~~ <--- HERE
        return input
  File "/home/khasaa/miniconda3/envs/RF2/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)
               ~~~~~~~~ <--- HERE
RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float

**Comment by jaideepm009** [comment]
having the same issues for some pdb files

**Comment by Khas-Erdene-1** [comment]
Turned out our machine graphics memory is not enough for bigger proteins like bigger than 1200 amino acids, so I'm closing this issue. Also RF2 doesn't allow multi graphics unit to predict.
