### ISSUE TITLE
No module named 'se3_transformer'

### ISSUE THREAD

**Issue by kimdn** [uw-ipd/RoseTTAFold2#5]
I see
```

(RF2) [kimd999@tlogin3 examples]$ ../run_RF2.sh rcsb_pdb_7UGF.fasta -o 7UGF_by_tmux

Running HHblits
 -> Running command: /home/kimd999/script/python/RoseTTAFold2/input_prep/make_protein_msa.sh 7UGF_by_tmux/rcsb_pdb_7UGF_1.fa 7UGF_by_tmux rcsb_pdb_7UGF_1 8 64
Running RoseTTAFold2 to predict structures
 -> Running command: python /home/kimd999/script/python/RoseTTAFold2/network/predict.py -inputs 7UGF_by_tmux/rcsb_pdb_7UGF_1.msa0.a3m  -
prefix 7UGF_by_tmux/models/model -model /home/kimd999/script/python/RoseTTAFold2/network/weights/RF2_apr23.pt -db /home/kimd999/script/p
ython/RoseTTAFold2/pdb100_2021Mar03/pdb100_2021Mar03 -symm C1
Traceback (most recent call last):
  File "/home/kimd999/script/python/RoseTTAFold2/network/predict.py", line 8, in <module>
    from RoseTTAFoldModel  import RoseTTAFoldModule
  File "/home/kimd999/script/python/RoseTTAFold2/network/RoseTTAFoldModel.py", line 3, in <module>
    from Embeddings import MSA_emb, Extra_emb, Templ_emb, Recycling
  File "/home/kimd999/script/python/RoseTTAFold2/network/Embeddings.py", line 9, in <module>
    from Track_module import PairStr2Pair
  File "/home/kimd999/script/python/RoseTTAFold2/network/Track_module.py", line 9, in <module>
    from SE3_network import SE3TransformerWrapper
  File "/home/kimd999/script/python/RoseTTAFold2/network/SE3_network.py", line 9, in <module>
    from se3_transformer.model import SE3Transformer
ModuleNotFoundError: No module named 'se3_transformer'
```

This is weird since I followed directions.

```
(RF2) [kimd999@tlogin3 SE3Transformer]$ which pip
alias pip='/home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/bin/pip'
	~/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/bin/pip

(RF2) [kimd999@tlogin3 SE3Transformer]$ pip install --no-cache-dir -r requirements.txt

Collecting dllogger
  Cloning https://github.com/NVIDIA/dllogger to /tmp/pip-install-671fjn3u/dllogger_4eb8e1a36a0442c69e875dff0aaf45a7
  Running command git clone --quiet https://github.com/NVIDIA/dllogger /tmp/pip-install-671fjn3u/dllogger_4eb8e1a36a0442c69e875dff0aaf45a7
  Resolved https://github.com/NVIDIA/dllogger to commit 0540a43971f4a8a16693a9de9de73c1072020769
  Preparing metadata (setup.py) ... done
Requirement already satisfied: e3nn==0.3.3 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.3.3)
Requirement already satisfied: wandb==0.12.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.12.0)
Requirement already satisfied: pynvml==11.0.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (11.0.0)
Requirement already satisfied: sympy in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from e3nn==0.3.3->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: scipy in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from e3nn==0.3.3->-r requirements.txt (line 1)) (1.10.1)
Requirement already satisfied: torch>=1.8.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from e3nn==0.3.3->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: opt-einsum-fx in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from e3nn==0.3.3->-r requirements.txt (line 1)) (0.1.4)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (2.8.2)
Requirement already satisfied: docker-pycreds>=0.4.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (0.4.0)
Requirement already satisfied: pathtools in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (0.1.2)
Requirement already satisfied: sentry-sdk>=1.0.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (1.24.0)
Requirement already satisfied: requests<3,>=2.0.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: shortuuid>=0.5.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (1.0.11)
Requirement already satisfied: six>=1.13.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: psutil>=5.0.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (5.9.5)
Requirement already satisfied: promise<3,>=2.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (2.3)
Requirement already satisfied: subprocess32>=3.5.3 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (3.5.4)
Requirement already satisfied: GitPython>=1.0.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (3.1.31)
Requirement already satisfied: protobuf>=3.12.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (4.23.2)
Requirement already satisfied: configparser>=3.8.1 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (5.3.0)
Requirement already satisfied: PyYAML in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (6.0)
Requirement already satisfied: Click!=8.0.0,>=7.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from wandb==0.12.0->-r requirements.txt (line 2)) (8.1.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from GitPython>=1.0.0->wandb==0.12.0->-r requirements.txt (line 2)) (4.0.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.12.0->-r requirements.txt (line 2)) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.12.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.12.0->-r requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.12.0->-r requirements.txt (line 2)) (1.26.15)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (8.5.0.96)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (10.2.10.91)
Requirement already satisfied: networkx in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (11.4.0.1)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (2.14.3)
Requirement already satisfied: triton==2.0.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: filelock in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (3.12.0)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (11.7.99)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (10.9.0.58)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (11.7.4.91)
Requirement already satisfied: jinja2 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (11.7.91)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (11.7.101)
Requirement already satisfied: typing-extensions in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (4.6.2)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (11.7.99)
Requirement already satisfied: setuptools in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (65.6.3)
Requirement already satisfied: wheel in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (0.38.4)
Requirement already satisfied: cmake in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (3.26.3)
Requirement already satisfied: lit in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (16.0.5)
Requirement already satisfied: packaging in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from opt-einsum-fx->e3nn==0.3.3->-r requirements.txt (line 1)) (23.0)
Requirement already satisfied: opt-einsum in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from opt-einsum-fx->e3nn==0.3.3->-r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from scipy->e3nn==0.3.3->-r requirements.txt (line 1)) (1.24.3)
Requirement already satisfied: mpmath>=0.19 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from sympy->e3nn==0.3.3->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb==0.12.0->-r requirements.txt (line 2)) (5.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages (from jinja2->torch>=1.8.0->e3nn==0.3.3->-r requirements.txt (line 1)) (2.1.2)

```
```

(RF2) [kimd999@tlogin3 SE3Transformer]$ which python
alias python='/home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/bin/python3.10'
	~/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/bin/python3.10

(RF2) [kimd999@tlogin3 SE3Transformer]$ python setup.py install

running install
/home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing se3_transformer.egg-info/PKG-INFO
writing dependency_links to se3_transformer.egg-info/dependency_links.txt
writing top-level names to se3_transformer.egg-info/top_level.txt
reading manifest file 'se3_transformer.egg-info/SOURCES.txt'
adding license file 'LICENSE'
adding license file 'NOTICE'
writing manifest file 'se3_transformer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/utils.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/__init__.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/test_equivariance.py -> build/bdist.linux-x86_64/egg/tests
creating build/bdist.linux-x86_64/egg/se3_transformer
creating build/bdist.linux-x86_64/egg/se3_transformer/model
creating build/bdist.linux-x86_64/egg/se3_transformer/model/layers
copying build/lib/se3_transformer/model/layers/norm.py -> build/bdist.linux-x86_64/egg/se3_transformer/model/layers
copying build/lib/se3_transformer/model/layers/linear.py -> build/bdist.linux-x86_64/egg/se3_transformer/model/layers
copying build/lib/se3_transformer/model/layers/pooling.py -> build/bdist.linux-x86_64/egg/se3_transformer/model/layers
copying build/lib/se3_transformer/model/layers/attention.py -> build/bdist.linux-x86_64/egg/se3_transformer/model/layers
copying build/lib/se3_transformer/model/layers/__init__.py -> build/bdist.linux-x86_64/egg/se3_transformer/model/layers
copying build/lib/se3_transformer/model/layers/convolution.py -> build/bdist.linux-x86_64/egg/se3_transformer/model/layers
copying build/lib/se3_transformer/model/fiber.py -> build/bdist.linux-x86_64/egg/se3_transformer/model
copying build/lib/se3_transformer/model/transformer.py -> build/bdist.linux-x86_64/egg/se3_transformer/model
copying build/lib/se3_transformer/model/__init__.py -> build/bdist.linux-x86_64/egg/se3_transformer/model
copying build/lib/se3_transformer/model/basis.py -> build/bdist.linux-x86_64/egg/se3_transformer/model
creating build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/runtime/inference.py -> build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/runtime/training.py -> build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/runtime/utils.py -> build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/runtime/arguments.py -> build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/runtime/callbacks.py -> build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/runtime/gpu_affinity.py -> build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/runtime/__init__.py -> build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/runtime/loggers.py -> build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/runtime/metrics.py -> build/bdist.linux-x86_64/egg/se3_transformer/runtime
copying build/lib/se3_transformer/__init__.py -> build/bdist.linux-x86_64/egg/se3_transformer
creating build/bdist.linux-x86_64/egg/se3_transformer/data_loading
copying build/lib/se3_transformer/data_loading/data_module.py -> build/bdist.linux-x86_64/egg/se3_transformer/data_loading
copying build/lib/se3_transformer/data_loading/qm9.py -> build/bdist.linux-x86_64/egg/se3_transformer/data_loading
copying build/lib/se3_transformer/data_loading/__init__.py -> build/bdist.linux-x86_64/egg/se3_transformer/data_loading
byte-compiling build/bdist.linux-x86_64/egg/tests/utils.py to utils.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_equivariance.py to test_equivariance.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/layers/norm.py to norm.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/layers/linear.py to linear.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/layers/pooling.py to pooling.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/layers/attention.py to attention.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/layers/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/layers/convolution.py to convolution.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/fiber.py to fiber.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/transformer.py to transformer.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/model/basis.py to basis.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/runtime/inference.py to inference.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/runtime/training.py to training.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/runtime/utils.py to utils.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/runtime/arguments.py to arguments.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/runtime/callbacks.py to callbacks.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/runtime/gpu_affinity.py to gpu_affinity.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/runtime/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/runtime/loggers.py to loggers.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/runtime/metrics.py to metrics.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/data_loading/data_module.py to data_module.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/data_loading/qm9.py to qm9.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/se3_transformer/data_loading/__init__.py to __init__.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying se3_transformer.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying se3_transformer.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying se3_transformer.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying se3_transformer.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/se3_transformer-1.0.0-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing se3_transformer-1.0.0-py3.10.egg
Removing /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages/se3_transformer-1.0.0-py3.10.egg
Copying se3_transformer-1.0.0-py3.10.egg to /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages
se3-transformer 1.0.0 is already the active version in easy-install.pth

Installed /home/kimd999/bin/Miniconda3-py310_23.3.1-0-Linux-x86_64/lib/python3.10/site-packages/se3_transformer-1.0.0-py3.10.egg
Processing dependencies for se3-transformer==1.0.0
Finished processing dependencies for se3-transformer==1.0.0
```

Any advice/suggestion/speculation will be appreciated.

**Comment by kimdn** [comment]
Even fresh re-installation (i.g. removal of RF2 conda environment and redo all) resulted in the same.

**Comment by kimdn** [comment]
Adding
```
import sys
sys.path.append("/home/kimd999/script/python/RoseTTAFold2/SE3Transformer")

```

at /home/kimd999/script/python/RoseTTAFold2/network/SE3_network.py
solved.

But then,
```
File "/home/kimd999/script/python/RoseTTAFold2/SE3Transformer/se3_transformer/model/basis.py", line 28, in <module>
    import e3nn.o3 as o3
ModuleNotFoundError: No module named 'e3nn'

```

appeared. 

So I had to install e3nn (not by 
`pip install e3nn==0.0.2`
which failed to install e3nn).
